version: '3.7'
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.3.6
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 29092:29092
    volumes:
      - redpanda:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy|OK'"]
      interval: 10s
      timeout: 5s
      retries: 5

  console:
    image: docker.redpanda.com/redpandadata/console:v3.5.0
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: 
      - -c
      - "echo \"kafka:\n  brokers: redpanda:29092\n\" > /tmp/config.yml; /app/console -config.filepath=/tmp/config.yml"
    ports:
      - 8080:8080
    depends_on:
      - redpanda

volumes:
  redpanda:
